# Generated by Django 4.0.6 on 2022-07-05 19:14

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='name')),
                ('slug', models.SlugField(editable=False, max_length=127, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to='brands/', verbose_name='image')),
                ('ordering', models.IntegerField(default=products.models.get_last_brand_ordering, verbose_name='ordering')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brand',
                'ordering': ('ordering',),
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True, verbose_name='slug')),
                ('ordering', models.IntegerField(blank=True, default=products.models.get_last_category_ordering, null=True, verbose_name='ordering')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category', to='products.productcategory', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-ordering', 'name'),
            },
        ),
    ]
